//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RicercaPratiche.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpvB02DettaglioPratica
    {
        public int IdRichiesta { get; set; }
        public string CodiceFascicolo { get; set; }
        public string CodicePratica { get; set; }
        public string NumeroIntervento { get; set; }
        public string Ordinanza { get; set; }
        public string IstruttoreUSR { get; set; }
        public string EmailIstruttoreUSR { get; set; }
        public string GruppoIstruttoreUSR { get; set; }
        public Nullable<int> IdUtenteIstruttoreUSR { get; set; }
        public Nullable<int> IdUtenteIstruttoreSAL { get; set; }
        public string IstruttoreSAL { get; set; }
        public string EmailIstruttoreSAL { get; set; }
        public string GruppoIstruttoreSAL { get; set; }
        public Nullable<int> NumProtocollo { get; set; }
        public Nullable<System.DateTime> DataProtocollo { get; set; }
        public Nullable<int> NumPrimoProtocollo { get; set; }
        public Nullable<System.DateTime> DataPrimoProtocollo { get; set; }
        public string Intestatario { get; set; }
        public string CodiceFiscaleIntestatario { get; set; }
        public string Progettista { get; set; }
        public string CodiceFiscaleProgettista { get; set; }
        public string Pec_Tecnico { get; set; }
        public string IstatComune { get; set; }
        public string Comune { get; set; }
        public string Provincia { get; set; }
        public string Foglio { get; set; }
        public string Mappale { get; set; }
        public string Indirizzo { get; set; }
        public string DestinazioneUso { get; set; }
        public string LivelloOperativo { get; set; }
        public string Casa_1_2 { get; set; }
        public string ImpresaAppaltatrice { get; set; }
        public string ImpresaAppaltatricePartitaIva { get; set; }
        public string ImpresaAppaltatriceCodiceFiscale { get; set; }
        public Nullable<System.DateTime> DataInvioChecklistComune { get; set; }
        public Nullable<System.DateTime> DataAvvisoRigetto1 { get; set; }
        public int PraticaRigettata { get; set; }
        public Nullable<System.DateTime> DataInizioIstruttoriaUSR { get; set; }
        public Nullable<System.DateTime> DataTrasmissioneAComune { get; set; }
        public Nullable<System.DateTime> DataSospensionePerimetrazioni { get; set; }
        public Nullable<System.DateTime> DataRilascioPdC { get; set; }
        public Nullable<System.DateTime> DataScadenzaRispostaComune { get; set; }
        public Nullable<System.DateTime> DataPrimaRichiestaIntComune { get; set; }
        public Nullable<System.DateTime> DataUltimaRichiestaIntComune { get; set; }
        public Nullable<System.DateTime> DataRicezioneUltimaIntComune { get; set; }
        public Nullable<System.DateTime> DataSanatoria { get; set; }
        public int SanatoriaCompletata { get; set; }
        public Nullable<System.DateTime> DataRichiestaConferenzaReg { get; set; }
        public Nullable<System.DateTime> DataConvocazioneConferenzaReg { get; set; }
        public Nullable<System.DateTime> DataEsitoConferenzaReg { get; set; }
        public Nullable<System.DateTime> DataAttestatoAvvenutoDeposito { get; set; }
        public Nullable<System.DateTime> DataPrimaRichiestaIntUSR { get; set; }
        public Nullable<System.DateTime> DataUltimaRichiestaIntUSR { get; set; }
        public Nullable<System.DateTime> DataRicezioneUltimaIntUSR { get; set; }
        public Nullable<System.DateTime> DataAvvisoRigetto2 { get; set; }
        public Nullable<System.DateTime> DataTrasmDecretoRigetto { get; set; }
        public Nullable<System.DateTime> DataAutProrogaFL { get; set; }
        public string NumDecretoContributo { get; set; }
        public Nullable<System.DateTime> DataDecretoContributo { get; set; }
        public Nullable<decimal> ContributoConcesso { get; set; }
        public string NumDecretoRideterminato { get; set; }
        public Nullable<System.DateTime> DataDecretoRideterminato { get; set; }
        public Nullable<System.DateTime> DataPresentazioneSal0 { get; set; }
        public Nullable<System.DateTime> DataPresentazioneSal20 { get; set; }
        public Nullable<System.DateTime> DataPresentazioneSal40 { get; set; }
        public Nullable<System.DateTime> DataPresentazioneSal50 { get; set; }
        public Nullable<System.DateTime> DataPresentazioneSal70 { get; set; }
        public Nullable<System.DateTime> DataPresentazioneSalFL { get; set; }
        public Nullable<System.DateTime> DataRichiestaProrogaFL { get; set; }
        public Nullable<System.DateTime> DataUltimaRichiestaIntSAL { get; set; }
        public Nullable<System.DateTime> DataUltimaIntSal0 { get; set; }
        public Nullable<System.DateTime> DataUltimaIntSal20 { get; set; }
        public Nullable<System.DateTime> DataUltimaIntSal40 { get; set; }
        public Nullable<System.DateTime> DataUltimaIntSal50 { get; set; }
        public Nullable<System.DateTime> DataUltimaIntSal70 { get; set; }
        public Nullable<System.DateTime> DataUltimaIntSalFL { get; set; }
        public Nullable<decimal> ContributoRichiesto { get; set; }
        public Nullable<decimal> ContributoRideterminato { get; set; }
        public Nullable<decimal> ContributoAmmissibile { get; set; }
        public Nullable<decimal> ContributoLiquidato { get; set; }
        public Nullable<int> NumSalPresentati { get; set; }
        public Nullable<System.DateTime> DataDecretoSal0 { get; set; }
        public string NumeroDecretoSal0 { get; set; }
        public Nullable<decimal> ImportoSal0Anticipo { get; set; }
        public Nullable<decimal> ImportoSal0Spese { get; set; }
        public Nullable<decimal> ImportoSal0Totale { get; set; }
        public Nullable<System.DateTime> DataDecretoSal20 { get; set; }
        public string NumeroDecretoSal20 { get; set; }
        public Nullable<decimal> ImportoSal20Totale { get; set; }
        public Nullable<System.DateTime> DataDecretoSal40 { get; set; }
        public string NumeroDecretoSal40 { get; set; }
        public Nullable<decimal> ImportoSal40Totale { get; set; }
        public Nullable<System.DateTime> DataDecretoSal50 { get; set; }
        public string NumeroDecretoSal50 { get; set; }
        public Nullable<decimal> ImportoSal50Totale { get; set; }
        public Nullable<System.DateTime> DataDecretoSal70 { get; set; }
        public string NumeroDecretoSal70 { get; set; }
        public Nullable<decimal> ImportoSal70Totale { get; set; }
        public Nullable<System.DateTime> DataDecretoSalFL { get; set; }
        public string NumeroDecretoSalFL { get; set; }
        public Nullable<decimal> ImportoSalFLTotale { get; set; }
        public int RitiroDomanda { get; set; }
        public string StatoPratica { get; set; }
        public string CodStatoPratica { get; set; }
        public int IsVariante { get; set; }
        public string SubAlterno1 { get; set; }
        public string SubAlterno2 { get; set; }
        public string SubAlterno3 { get; set; }
        public string SubAlterno4 { get; set; }
        public string CodiceAteco { get; set; }
        public Nullable<System.DateTime> DataPresaInCaricoMIS { get; set; }
        public string Cup { get; set; }
    }
}
